from setuptools import setup, find_packages

setup(
    name='ranpick',
    version='2.1.0',
    author='rainy58',
    author_email='yhg4908@kakao.com',
    description='A high-entropy random number generation library',
    long_description=open('README.md').read() if open('README.md', 'r').read() else '',
    long_description_content_type='text/markdown',
    url='https://github.com/yhg4908/ranpick.py',
    packages=find_packages(),
    install_requires=[],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
    ],
    python_requires='>=3.7',
    package_data={'': ['LICENSE', 'README.md', 'README_KR.md', 'UPDATE.md']},
    keywords='random number generation entropy ranpick list Probability',
)
